### ISSUE TITLE
Package.js missing deps

### ISSUE THREAD

**Issue by RobertLowe** [meteor-useraccounts/polymer#3]
This may be more of a `core` issue, but:

I ran into a couple issues when adding `core`/`polymer`. Most importantly there are zero warnings if you don't have excepted dependancies installed.

`accounts-password` is required for passwords, but still display regardless if it's installed or not. The sign in form silently fails.

`accounts-base` is required, but not `api.use`'d or `api.imply`'d 

`service-configuration` is required for service configuration for oauth packages.

`accounts-{{oauth}}` is required for the services to work regardless of setup w/ service configuration.

So, I think; based on the features you want to use, the package should warn you if they're missing. 

I think `accounts-password`/`accounts-base`/`service-configration` can all be safely `api.imply`'d by the `core` package.

Thoughts?

**Comment by splendido** [comment]
Hi @RobertLowe!

Yes, this is more a core issue, but I'll try to answer.

The polymer version is currently run by @kevohagan, (which still has to beautify a little more the README.md file... are you reading Kevin? ;-) ) and is still WIP, even if already colmpleted for most of the parts. So please be a little patient and help us bringin it to a final working state (which you're actually doing right now, tnx)
- In all useraccounts packages there are no frontend deps (lets have a look at [this section](https://github.com/meteor-useraccounts/semantic-ui#bring-your-own-semantic-ui) for example which is usually included for all packages)
  (are you reading Kevin? ;-) )
- if the `atPwdForm` part of the template (the one with input fields for the password...) is being shown even if `accounts-password` is not among the available packages, **this is a bug**! I'll try to verify that this is still true for the other packages, but used to work well so far...
- as soon as you add  `accounts-password`, also `accounts-base` is added as a dependency
- the same applyes to `accounts-oauth` which is added as a dependency of any social login packages (`accounts-google`, `accounts-facebook`, etc.)
- as soon as you add a social oauth service you'll see its login/register button popping up at the top of the `atForm` and you should know that to get it configured you need also `service-configuration` (which conversely you don't need if you're not interested in OAuth flows...)

Do you think this can be grasped also from the [Setup](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#setup) section of the [Guide](https://github.com/meteor-useraccounts/core/blob/master/Guide.md)?
...actually there's also a [3rd Party Login Services Configuration](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#3rd-party-login-services-configuration) section which perhaps should be linked from the previous one?

Let me know if this makes any sense.
Thanks!

**Comment by RobertLowe** [comment]
> is still WIP, even if already completed for most of the parts. So please be a little patient and help us bringin it to a final working state (which you're actually doing right now, tnx)

I will, I'll probably have pulls in the future; just pointing out issues I'm running into. =)

> Do you think this can be grasped also from the Setup section of the Guide?

@splendido Sure, the guide is one thing, but I see no sensibility in silent errors.

As for `accounts-password` & `accounts-{{oauth}}` it's probably a good idea to log a simple message when they aren't found but expected. Something like: `console.warn("You're using passwords but you didn't install it! Run: 'meteor add accounts-password' to resolve this warning")` when excepted by missing.

Just my two cents.

Cheers
- Rob

**Comment by splendido** [comment]
2 cents much appreciated actually!

...to tell you all the story, I'm reasoning on a v2.0 since a couple of months ago and what I'm visualizing is a big refactor using a set of pacakges and one of plug-in packages with a very well poundered dependencies organization.

In your situation I'd say you could have to do something like:

``` shell
meteor add useraccounts:polymer
meteor add useraccounts:password
```

or 

``` shell
meteor add useraccounts:polymer
meteor add useraccounts:oauth
meteor add accounts-google
```

which should be self explicative ;-) but:
- `useraccounts:password` should bring in the `atPwdForm` functionality and depends on `accounts-password` (no more need to add it by hand then...)
- `useraccounts:oauth` should do the same for the OAuth flows bringing in `accounts-oauth` and `service-configurator`

In this case you'll have a chance to pick up the user intent and warn about any missing packages.

For example if you forgot to add `accounts-google` in the second example you could easily discover that the number of available services is zero and warn the user to add at lease one of them.

Do you think this scenario would be any better?

**Comment by RobertLowe** [comment]
It's difficult to say; I've found building multi-package packages to be awkward. 

I did recently see some good concepts / practices in [reaction](https://github.com/reactioncommerce/reaction-core) - [conventions](https://reactioncommerce.com/guide/reaction-core/conventions) and [templates](https://reactioncommerce.com/guide/reaction-core/templates). 

I find handling for bootstrap/polymer/foundations/etc to be a be fumble-some. Mainly due to how functionality must be share and how it cannot be shared/namespaced (helpers are not shared with child templates, global helpers are _global_), but small issues like that aside it's still terse to solve.

Maybe a user story would be helpful:

As a user, I want to easily add accounts to my application. I also want to be able to easily support different frontend frameworks (polymer/bootstrap/etc). It should be flexible for me because the needs of my application may vary. I may also want to use a different array of authentication mechanisms (passwords, oauth, etc).

Hmm, so yea maybe:

`useraccounts:core` - common functionality usable by any `useraccounts` package (depends on accounts-base)
`useraccounts:ui` - generic ui implementations, pools together other package `passwords`, `oauth`, it would also pull together `enrollment` and `verify email` for example (depends on core)
`useraccounts:password` - UI for passwords (sign in / sign up / change password / reset password) (adds accounts-password, depends on ui)
`useraccounts:oauth`  - UI support for oauth implementations (adds service configuration & accounts-oauth, depends on ui)

`useraccounts:polymer` supplements `usersaccounts:password`/`useraccounts:oauth` with new templates (using: [template extensions's replaces](https://github.com/aldeed/meteor-template-extension#replacestemplatename)) (depends on passwords/oauth)

What do you think?

**Comment by splendido** [comment]
Well, at a first glance, I don't see it much different from my above proposal.
The optimal situation would be for the developer to run `meteor add <something>` as few time as possible, so in principle

`meteor add useraccounts:polymer`

should give you something ready and working (with already configured routes which, in case, you can later remove, ans some basic functionality...).

The problem is that of you make it depends on `useraccounts:password` you will not able to remove it later on, and not all devs out there are interested in having also the password login.
The same applies for the OAuth part.

Then you might (as a developer) add _advanced_ functionalities:
- useraccounts:email to get forgot password, enroll account, etc, pages pop up and possibly configuring your email service (defaulting to the `email` package)
- useraccounts:invites to deal with new user invitations
- useraccounts:rechaptcha
- useraccounts:dfa
- useraccounts:modals
- useraccounts:meld
- useraccounts:guest
- useraccounts:registration-code
- useraccounts:fview-wrapper

but all this should be added in a second time, independently from the framework you choosed.

About `aldeed:template-extension`, I would prefer not to use it to leave the code payload as leas as possible.
Already now all helpers, event handlers and core logic are separated from the html and are flawlessly _inherited_ by the available templates.

If you wish to get an idea about the package structure I'm trying to design, there's a first test I've done a bit of time ago [here](https://github.com/splendido/meteor-modular-class)

**Comment by RobertLowe** [comment]
> The problem is that of you make it depends on useraccounts:password you will not able to remove it later on, and not all devs out there are interested in having also the password login.
> The same applies for the OAuth part.

I don't see the harm in having say `polymer` depend on `password`/`oauth` and adding an flags for their use:

```
AT.config({
  usePasswords: false, // defaults true
  // defaults true, has no-effect if no `accounts-{{oauth}}` added, should probably warn
  // if usePasswords=false & no oauth packages detected
  useOauth: true 
});
```

What do you think?

> About aldeed:template-extension, I would prefer not to use it to leave the code payload as leas as possible.

Yea, that's fine

**Comment by splendido** [comment]
Seems a potentially good DX (develop experience ;-) )!
But I'm a bit concerned about adding packages that are not needed...
...in the end they all will be bundled with the app code and shipped to the client on page load.

Do you think this is not a point to be considered?
...or perhaps the added payload would be just a few bytes?
I'm almost sure someone will complain about this! ;-)

**Comment by splendido** [comment]
v2.0 development is starting, lets keep an eye on [this](https://trello.com/b/NWHVV4ZA/useraccounts-2-0-roadmap)
